# Generated by Django 5.2 on 2026-08-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20),
        ),
    ]
