# Generated by Django 5.2 on 2026-07-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
